### ISSUE TITLE
May be found typo

### ISSUE THREAD

**Issue by khibino** [krdlab/haskell-oidc-client#14]
Is this typo?
'oidcAuthorizationSeverUrl'
Should this be fixed to 
'oidcAuthorizationServerUrl' ?

https://github.com/krdlab/haskell-oidc-client/blob/5b4e4e3/src/Web/OIDC/Client/Settings.hs#L23

**Comment by krdlab** [comment]
Yes, it's typo. Thank you for your report.
I will fix it sometime soon.
