### ISSUE TITLE
Discovery broken because of malformed url

### ISSUE THREAD

**Issue by Akii** [krdlab/haskell-oidc-client#38]
Hi,

currently `discover` is broken because the URL that is generated for discovery includes an additional slash. Instead of

`https://issuer.tld/.well-known/openid-configuration`

the url

`https://issuer.tld//.well-known/openid-configuration`

is generated leading to a JSON decode failure.

The issue is here:
https://github.com/krdlab/haskell-oidc-client/blob/master/src/Web/OIDC/Client/Discovery.hs#L53

```
appendPath ".well-known/openid-configuration" req
```

works like a charm.

**Comment by krdlab** [comment]
Hmm... I cannot reproduce the issue. 🤔

**Comment by Akii** [comment]
Hi, so I double checked this. For this I used `stack ghci` in this project to ensure I use the exact package versions that the compiled library would use.

```
> :l Web.OIDC.Client.Discovery
> :set -XOverloadedStrings
> parseUrl "https://some-path.eu.auth0.com"
```

results in the following parsed request:

```
Request {
  host                 = "some-path.eu.auth0.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
```

After that I apply `appendPath` on that request:

```
> appendPath suffix req = req { path = path req `append` suffix }
> appendPath "/.well-known/openid-configuration" req 
```

That results in the following request:

```
Request {
  host                 = "some-path.eu.auth0.com"
  -- ...
  path                 = "//.well-known/openid-configuration"
  -- ...
}
```

On Auth0 this results in an invalid request.

**Comment by krdlab** [comment]
@Akii 
Oops! my mistake. I had not noticed this problem because to call `discover` function was successful with other IdPs.

Thank you so much! 🙇
