### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by chris-martin** [krdlab/haskell-oidc-client#62]
The switch from `cryptonite` to `crypton` does not yet appear in a release - would you mind releasing the current code to Hackage?

**Comment by krdlab** [comment]
Thank you for reminding me. I will release it in a few days.

**Comment by krdlab** [comment]
I've released [oidc-client-0.8.0.0](https://hackage.haskell.org/package/oidc-client-0.8.0.0).

**Comment by chris-martin** [comment]
Thank you! :smile:
