### ISSUE TITLE
Text 2.1 is out of bounds

### ISSUE THREAD

**Issue by chris-martin** [krdlab/haskell-oidc-client#63]
The latest release of `oidc-client` has an upper bound on `text` that excludes version 2.2, but it does build with text 2.2.

**Comment by bmillwood** [comment]
The Hackage page for [text](https://hackage.haskell.org/package/text) suggests the latest version is `text-2.1.1`. I'm guessing this issue intended to refer to version 2.1, since that's what the PR referencing this issue achieves.

**Comment by chris-martin** [comment]
Yes, surely a typo on my part. Adjusted the issue title, and closing it.
